name: brightcove_android
description: A new Flutter project.
version: 0.1.0
homepage:
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  brightcove_flutter_platform_interface:
    # path: ../brightcove_flutter_platform_interface
    git:
      url: https://github.com/Genieology/brightcove_flutter.git
      path: brightcove_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^4.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: brightcove_flutter
    platforms:
      android:
        dartPluginClass: BrightcoveAndroidPlatform
        package: com.monstarlab.brightcove_android
        pluginClass: BrightcoveAndroidPlugin