name: brightcove_flutter_platform_interface
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.0