name: brightcove_flutter_platform_interface
description: Interface implementation for the Brightcove plugin
version: 0.0.1
repository: https://github.com/Genieology/brightcove_flutter/tree/main/brightcove_flutter_platform_interface
homepage: https://github.com/Genieology/brightcove_flutter/tree/main/brightcove_flutter_platform_interface

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.0