name: brightcove_flutter
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: brightcove_android

dependencies:
  flutter:
    sdk: flutter
  brightcove_android:
    path: ../brightcove_android
  brightcove_flutter_platform_interface:
    path: ../brightcove_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
