name: brightcove_flutter
description: A new Flutter project.
version: 0.0.1
homepage:
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: brightcove_android

dependencies:
  flutter:
    sdk: flutter
  brightcove_android:
    git:
      url: git@github.com:Genieology/brightcove_flutter.git
      path: brightcove_android
      ref: v0.0.1

dependency_overrides:
  brightcove_flutter_platform_interface:
    git:
      url: git@github.com:Genieology/brightcove_flutter.git
      path: brightcove_flutter_platform_interface
      ref: v0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
