name: brightcove_flutter
description: A new Flutter project.
version: 0.1.0
homepage:
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: brightcove_android
      ios:
        default_package: brightcove_ios

dependencies:
  flutter:
    sdk: flutter
  brightcove_android:
    # path: ../brightcove_android
    git:
      url: https://github.com/Genieology/brightcove_flutter.git
      path: brightcove_android
      ref: v0.2.1
  brightcove_ios:
    # path: ../brightcove_ios
    git:
      url: https://github.com/Genieology/brightcove_flutter.git
      path: brightcove_ios
      ref: v0.2.1

dependency_overrides:
  brightcove_flutter_platform_interface:
    # path: ../brightcove_flutter_platform_interface
    git:
      url: https://github.com/Genieology/brightcove_flutter.git
      path: brightcove_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
